### PR TITLE
Issue  90 Golden JSON Copy

### PR DESCRIPTION
**Pull request by dsmith111**
### Summary
07-26-2021
Merged existing data collections into a single JSON file and used the MAG API to fill in missing data. This PR includes the JSON file and the script which performed the CSV to JSON conversion + MAG API integration.

09-13-2021
Attached golden.json file produced from pipeline along with validation report. Update doi scraper to handle more cases.
[example_report_09-13-2021-03_39_52.zip](https://github.com/nasa-petal/data-collection-and-prep/files/7155343/example_report_09-13-2021-03_39_52.zip)

### Related Issues

- Resolves Issue #90 

### Backwards incompatibilities

- None.

### New Dependencies

- python-decouple

### CODE REVIEW

**Review by hschilling — COMMENTED** [review]
In the description of the return value of get_arg_parser, maybe say is it class argparse.Namespace (https://docs.python.org/3/library/argparse.html#argparse.Namespace) instead of listing the method?

**Comment by hschilling** [comment]
Maybe put something in the readme about needing to do `nltk.download('stopwords')`

**Comment by hschilling** [comment]
a comment "Make DOI requests in batches of 20" says batch size 20 but code does 10

**Comment by hschilling** [comment]
I wonder if the clean_text function is always doing the right thing. It might not matter much but I saw that

`foam—túngara` got cleaned into `foamtngara` .

`túngara` is a type of frog

**Comment by dsmith111** [comment]
> I wonder if the clean_text function is always doing the right thing. It might not matter much but I saw that
> 
> `foam—túngara` got cleaned into `foamtngara` .
> 
> `túngara` is a type of frog

Yeah, that occurred with the scrubbing of all of the non-ascii characters. However, NLTK can handle tokenizing unicode, so we're going to leave it in instead, which should resolve that issue.

**Review by hschilling — APPROVED** [review]

**Pull request merged**
